name: ielts
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_screenutil: 5.0.0+2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  speech_to_text: ^6.1.0
  flutter_tts: ^3.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: icons
      fonts:
        - asset: assets/icons/Icons.ttf